### ISSUE TITLE
IId interface

### ISSUE THREAD

**Issue by rkotenko** [corstian/Boerman.GraphQL.Contrib#5]
Hi,

I found you posts about pagination for graphql and C# and have determined that your method suits me well. I was glad to see you even had a library available for me to use.  While trying to implement though, I ran into a problem with one of my types not being able to be cast as IId.  So I looked at your repo and saw that in one commit (https://github.com/corstian/Boerman.GraphQL.Contrib/commit/16f181ea5d021482ed7205cd721feee585d7472e), you removed IId from the ToConnection, and that you were making it obsolete.  But in the commit that follows, it seems the line is back to what it was before.  Oddly, there is no reference that it is being added back in,...the lines are equal in the commit comparison.

The version that I got from Nuget contains the IId requirement.  I can alway just clone your repo and mod as needed for my services if this was intentional.  Just though you might want to know though if it was not.

**Comment by corstian** [comment]
I see the issue there!

So I think I can take the blame here for lack of documentation. Having downloaded the latest version [from NuGet](https://www.nuget.org/packages/Boerman.GraphQL.Contrib/), and opening it with dnSpy, I could confirm the correct methods are available:

![image](https://user-images.githubusercontent.com/5021647/68199515-7b5be580-ffbe-11e9-95d9-20afbe011560.png)
 
Please note the different method definitions.

I would advice on using the `.ToConnection` method using the `Action<T, string>` to mark the way your cursor should be displayed in the edge objects. This is what the `IId` interface was previously used for, and the overload using this interface is currently mapped to the other one anyway:

```
return await query.ToConnection<T, TSource>(context, q => q.Id.ToCursor());
```

Though there is one more thing I realized when I wrote this, and that is that I made the assumption that an `Id` field will be available within the database which can be used to base the slices on. (This method is explained here: https://corstianboerman.com/2019-03-06/cursor-based-pagination-with-sql-server.html#implementation, look at the `column` argument.)

If this is an issue I would have to think about either using an `Expression` to get the field name, or to create another overload with which the primary column name can be defined.

Does this solve your issues for now?

**Comment by rkotenko** [comment]
Ahhh!  Yes. That seems to remove my error just fine.  

Thanks!
